### ISSUE TITLE
دریافت ۱۵ آگهی آخر با فیلتر خاص

### ISSUE THREAD

**Issue by vgggy34g55** [divar-ir/kenar-docs#45]
سلام
Api
میخوام
که
پانزده آگهی آخر با فیلتر خاص را هر ۱۵ دقیقه با فراخوانی دریافت کنم

یا وب هوک اگهی با فیلتر خاص را برای من ارسال کند

با کدوم بخش تماس بگیرم

**Comment by loreanvictor** [comment]
اول باید در پنل ثبت‌نام کنین (https://divar.ir/kenar)،   در گام بعدی  می ‌تونین از [این اندپوینت](https://github.com/divar-ir/kenar-docs/blob/master/finder/search_post.md) استفاده کنین.

اشاره کنم که استفاده از این اندپوینت صرفا جهت استفاده‌ی یک افزونه‌ی خاص مقدوره.

پ.ن. @ehsundar به نظر لینک مستندات اندپوینت‌های سرچ راحت پیدا نمی‌شن از صفحه‌ی اول. این ایشو رو خوبه باز نگه داریم تا این رو تصحیح کنیم.
