### ISSUE TITLE
دسترسی به شماره کاربران

### ISSUE THREAD

**Issue by alifarshadi** [divar-ir/kenar-docs#54]
سلام
سوالم اینه که من میتونم وقتی  API Key گرفتم به هر روشی خواستم شماره کابرای دیوار رو بر دارم (بدون اینکه اجازه بگیرم)؟
اخه خود من به شخصه تو دیوار آگهی میذارم سریع بعدش واسم یه تبلیغ اس ام اس میشه ک بیا اینجا آگهیتو بذار بهتر فروش میره 
داستانش چیه لطفا راهنماییم کنین.
من میخوام یه بانک شماره تلفن داشته باشم میتونم از دیوار استخراج کنم؟

**Comment by ehsundar** [comment]
سلام. توی پلتفرم باز دیوار اطلاعات حساس و غیر عمومی کاربران فقط با اجازه و رضایت صاحب اطلاعات در اختیار شخص ثالث قرار میگیره. شماره تلفن از این قاعده مستثنی نیست.

در مورد پیامک‌های تبلیغاتی و نشت احتمالی شماره‌ها، تیم دیگه‌ای توی دیوار روی این موضوع تمرکز کرده و بزودی برطرف خواهد شد.

**Comment by amirsalarsafaei** [comment]
با توجه به این اکتیو بودن ایشو من کلوزش میکنم
