### ISSUE TITLE
Assets 

### ISSUE THREAD

**Issue by jaavid** [divar-ir/kenar-docs#60]
با سلام
آیا است‌ها فقط همین موارد لیست شده در https://github.com/divar-ir/kenar-docs/tree/master/assets هستند؟
مثلا دسته بندی سفر و تور است برای انتخاب شهر مقصد ندارد؟

اندپوینتی برای گرفتن لیست تمام است‌ها
 (مثلا https://api.divar.ir/v1/open-platform/assets/index ) 
 موجود است؟

متشکرم.

**Comment by ehsundar** [comment]
سلام و درود

است‌های کنار دیوار فقط شامل همین موارد است و سایر موارد ممکن است بدرخواست شما اضافه شوند. لکن شهر مقصد در این دسته‌بندی از فیچرهای فعلی دیوار نیست در نتیجه در کنار دیوار هم وجود ندارد. البته که پیشنهاد شما را به تیم مربوط در دیوار منتقل خواهیم کرد.

سپاس از وقت و توجه شما

**Comment by jaavid** [comment]
متشکرم
