### ISSUE TITLE
 سند عمومی شرایط و مقررات نیاز به به‌روزرسانی دارد

### ISSUE THREAD

**Issue by jaavid** [divar-ir/kenar-docs#63]
این سند که در فایل policies.md به گوگل داکز لینک شده قدیمیه و هنوز به kenar.divar.ir اشاره میکنه

**Comment by ehsundar** [comment]
مرسی از همراهی شما. این مشکل رو طبق پیشنهاد شما فیکس کردم.

**Comment by jaavid** [comment]
متشکرم
