### ISSUE TITLE
حذف برنامه اعمال شده 

### ISSUE THREAD

**Issue by Mohammadf4f12** [divar-ir/kenar-docs#64]
عرض ادب و احترام . وقتی کاربر از بخش مکمل ها یه مکمل به آگهی اضافه میکنه ، برای حذف مکمل میتونه بدون وارد شدن به اپلیکیشن ما مکمل رو حذف کنه ؟ و اگر مکمل رو حذف کنه راهی هست که اپلیکیشن ما این رو متوجه بشه ؟ 

(میخوایم اگر مکملی که توسط برنامه ما ایجاد شده ، حذف شد ، ما مطلع بشیم . یا اینکه برای حذف مکمل ما ، کاربر مجبور باشه مجدد وارد اپلیکیشن ما بشه )
راهی وجود داره ؟

**Comment by saeedalipoor** [comment]
سلام وقت بخیر.
در حال حاضر کاربران از صفحهٔ دیوار من فقط امکان حذف کلی دسترسی‌ها و افزونه‌های درج شدهٔ هر اپ را دارند. (احتمال تغییر در آینده وجود دارد)
برای الان پیشنهاد می‌شه زمانی که نیاز به بررسی این موضوع دارید یکی از ریکوئست‌های GET که نیاز به access token دارند را صدا کنید و در صورت دریافت خطای دسترسی، کاربر را به فرایند OAuth بفرستید.
