### ISSUE TITLE
دریافت مشخصات کاربر

### ISSUE THREAD

**Issue by hamidkarimy** [divar-ir/kenar-docs#66]
با سلام. ایا مشخصات کاربری که میتونیم از دیوار بگیریم صرفا شماره تماس است؟ آیا نمیتوان مثلا در بحث املاک مشخص کرد که کاربر یک کاربر عادی است و یا مدیر املاک و یا کارشناس املاک؟

**Comment by Mohammadf4f12** [comment]
دوست عزیز ما تا به این لحظه حدود 200 میلیون روی پروژمون هزینه کردیم و واقعا وجود چنین چیزی توی اپی که داریم ضروری هستش ( درحال حاضر چیزی که نیاز داریم اینه که با کسب اجازه از کاربر ، متوجه بشیم که آیا این شخص  یک کاربر عادی ، مدیر املاک و یا کارشناس املاک هست ؟ )

حتی اگر این مورد هم براتون مقدور نیست . صرفا یه قابلیت در اختیار ما قراربدید که با کسب اجازه از کاربر ، چک کنیم ببینیم کاربر مدیر املاک هست یا خیر 

 ممنون .

**Comment by saeedalipoor** [comment]
در مورد اضافه شدن اسکوپ دریافت وضعیت کاربر در پنل‌ها (املاک، فروشگاه و ...) همون‌طور که گفته‌شد در لحظه این رو نداریم و برنامه‌ای هم در کوتاه‌مدت براش نداریم.

پیشنهاد می‌کنیم برای الان این مورد رو از خود کاربر بپرسید و پیش ببرید.
