### ISSUE TITLE
توسعه افزونه

### ISSUE THREAD

**Issue by meshkatit** [divar-ir/kenar-docs#67]
سلام. آیا میشه متناسب با هر کاربری که آگهی ثبت می کنه یک سرویسی بدیم که خود آگهی دهنده سفارشی سازی کنه و در صورتی که متقاضی آن سرویس وارد آگهی مورد نظر شود ، همان صفحه سفارشی سازی شده که خود آگهی دهنده خواسته رو به متقاضیان نشون بدیم. به این صورت که متقاضی یا مشاهده کننده آگهی در صورت کلیک یا لمس لینک ما وارد صفحه ای بشه که آگهی دهنده سفارشی سازی کرده است؟

**Comment by saeedalipoor** [comment]
سلام.
در حال حاضر بر اساس دستهٔ آگهی یا شهر می‌توانید افزونهٔ خود را در اختیار کاربران دیوار بگذارید.
مسیر دسترسی کاربران به افزونه‌ها را [اینجا](https://github.com/divar-ir/kenar-docs#%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%D8%B1%D9%88%DB%8C-%D8%A2%DA%AF%D9%87%DB%8C%D9%87%D8%A7-) ببینید.
