### ISSUE TITLE
سرچ کردن تمام شهر ها

### ISSUE THREAD

**Issue by Kiarash-Karami** [divar-ir/kenar-docs#68]
چگونه میشه داخل api بجای یک شهر تمام شهر‌های کشور رو بدیم

**Comment by saeedalipoor** [comment]
در حال حاضر فقط در یک شهر می‌توانید جستجو را انجام دهید و مقدار city در درخواست search فقط نام یک شهر می‌تواند باشد.
[مستندات جستجو](https://github.com/divar-ir/kenar-docs/blob/master/finder/search_post.md#%D8%AC%D8%B3%D8%AA%D8%AC%D9%88%DB%8C-%D8%A2%DA%AF%D9%87%DB%8C)
