### ISSUE TITLE
عدم دریافت توکن

### ISSUE THREAD

**Issue by hamidkarimy** [divar-ir/kenar-docs#75]
عرض ادب و احترام 

بعد از اینکه سرویس oath رو کال میکنیم و توی scope هم user_phone رو ست میکنیم ، یک کد دریافت میکنیم :

 با این کد میخواهیم توکن دریافت کنیم که با خطای invalid grant مواجه میشویم ( grant_type رو معادل چیزی که در داکیومنت هست ، برابر با authorization_code قرار میدهیم )

کل خطا به شرح زیر است :
"error": "invalid_grant",
   " error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."

**Comment by amirsalarsafaei** [comment]
فکر کنم به علت ست نکردن redirect_url درست oauth باشه
