### ISSUE TITLE
Upload link "could not check authorization" request failed

### ISSUE THREAD

**Issue by mostafa-kheibary** [divar-ir/kenar-docs#79]
من با api دیگه توکن خودم رو چک کردم و به درستی کار میکردن
تنها /v1/open-platform/post/image-upload-url ارور authorization و کد ۷ برمیگردوند

ایا استفاده از این api نیاز به permision خاصی داره؟
چون من تنها با ست کردن x-api-key,  به باقی api دسترسی داشتم و این مورد فقط مشکل داشت برام

**Comment by saeedalipoor** [comment]
برای آپلود تصویر با api-key اپ‌های فعال روی محصول نیاز به دریافت دسترسی دارید که می‌تونید از طریق تیکت در پنل کنار دیوار این درخواست بدین.
برای اپ‌های تستی **جدید** هم دسترسی آپلود تا ۳۰ تصویر وجود داره.

لطفا در پنل کنار درخواست ثبت کنید تا این دسترسی برای برنامهٔ شما فعال بشه.
