### ISSUE TITLE
 درخواست دسترسی به API دیوار

### ISSUE THREAD

**Issue by Hamzemollaie** [divar-ir/kenar-docs#85]
سلام تیم دیوار،

امیدوارم حالتان خوب باشد. به عنوان یک کاربر و علاقه‌مند به استفاده از خدمات دیوار، به دنبال دسترسی به API شما هستم.

هدف از این درخواست، بارگذاری و مدیریت محصولات به‌صورت خودکار در پلتفرم شماست. با استفاده از API، می‌توانم فرآیند ثبت محصولات را بهبود ببخشم و تجربه بهتری برای کاربرانم فراهم کنم.

لطفاً اگر امکانش هست، اطلاعات و مستندات لازم برای دسترسی به API دیوار را در اختیارم قرار دهید. همچنین اگر مراحلی وجود دارد که باید طی کنم، خوشحال می‌شوم از راهنمایی‌های شما بهره‌مند شوم.

از همکاری شما سپاسگزارم و منتظر پاسخ شما هستم.

**Comment by saeedalipoor** [comment]
سلام وقت بخیر
در حال حاضر امکان ثبت آگهی با API وجود ندارد.
تمام APIهای در دسترس در همین مخزن مستندات درج شده و قابل استفاده هستند.
