### ISSUE TITLE
نحوه ارسال درخواست به شهر خواص با پارانتر خواص

### ISSUE THREAD

**Issue by applecompe** [divar-ir/kenar-docs#92]
سلام
چطور میتونیم درخواستی بزنیم که مثلا توی شهر تهران هر آگهی که مربوط میشه به موبایل آپل رو بهمون نشون بده؟
ممنون میشم راهنمای کنید

**Comment by saeedalipoor** [comment]
از [این](https://github.com/divar-ir/kenar-docs/blob/master/finder/search_post.md) API می‌تونید استفاده کنید.
البته به زودی نسخهٔ جدیدش در دسترس قرار می‌گیره.
https://github.com/divar-ir/kenar-docs/blob/master/finder/search_post.md

**Comment by applecompe** [comment]
خیلی ممنون از راهنمایتون.
